services:
  db:
    image: postgres:17.0
    container_name: postgres-db
    environment:
      - POSTGRES_DB=go-api
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

